version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - redis_network

  scylla:
    image: scylladb/scylla
    ports:
      - "9042:9042"
      - "7001:7001"  # Изменен порт для ScyllaDB
      - "7199:7199"
      - "9160:9160"
    volumes:
      - scylla_data:/var/lib/scylla
    networks:
      - scylla_network

volumes:
  redis_data:
    driver: local
  scylla_data:
    driver: local

networks:
  redis_network:
  scylla_network:
