info:
  contact: {}
paths:
  /token/generateToken:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: successful response
          schema:
            additionalProperties: true
            type: object
      summary: Получение токена и uuid
      tags:
      - Tokens
  /token/get-public-key:
    get:
      parameters:
      - description: UUID пользователя
        in: query
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: successful response
          schema:
            additionalProperties: true
            type: object
      summary: Получение токена и публичного ключа по UUID
      tags:
      - Tokens
  /user/log-in:
    get:
      description: "2"
      produces:
      - application/json
      responses:
        "200":
          description: successful response
          schema:
            additionalProperties: true
            type: object
      summary: Функция для авторизации пользователя
swagger: "2.0"
