info:
  contact: {}
paths:
  /token/generateToken:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: successful response
          schema:
            additionalProperties: true
            type: object
      summary: Получение токена и uuid
      tags:
      - Tokens
  /token/get-public-key:
    get:
      parameters:
      - description: UUID пользователя
        in: query
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: successful response
          schema:
            additionalProperties: true
            type: object
      summary: Получение токена и публичного ключа по UUID
      tags:
      - Tokens
  /user/log-in-with-credentials:
    post:
      consumes:
      - application/json
      parameters:
      - description: UUID пользователя
        in: query
        name: uuid
        required: true
        type: string
      - description: Зашифрованный логин пользователя
        in: query
        name: login
        required: true
        type: string
      - description: Зашифрованный пароль пользователя
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: successful response
          schema:
            additionalProperties: true
            type: object
        "400":
          description: bad request
          schema:
            additionalProperties: true
            type: object
      summary: Аутентификация пользователя по логину и паролю
      tags:
      - Users
swagger: "2.0"
