definitions:
  chats.CreateChatStruct:
    description: Данные для создания чатов
    properties:
      companion_id:
        type: string
      user_id:
        type: string
      uuid:
        type: string
    type: object
  users.ErrorResponse:
    properties:
      error:
        type: string
      status:
        type: boolean
    type: object
  users.ResponseMessage:
    properties:
      Data:
        additionalProperties: true
        type: object
      message:
        type: string
      status:
        type: boolean
    type: object
  users.UserCT:
    description: User chekToken data structure.
    properties:
      pKey:
        type: string
      token:
        type: string
      uuid:
        type: string
    type: object
  users.UserCUD:
    description: Данные для проверки на уникальность данных
    properties:
      Login:
        type: string
      Nik:
        type: string
      uuid:
        type: string
    type: object
  users.UserLogin:
    description: User login data structure.
    properties:
      login:
        example: john_doe
        type: string
      pKey:
        type: string
      password:
        example: securePassword123
        type: string
      uuid:
        type: string
    type: object
  users.UserRegistration:
    description: User registration data structure.
    properties:
      login:
        example: john_doe
        type: string
      name:
        example: John
        type: string
      nik:
        example: JohnnyD
        type: string
      pKey:
        type: string
      password:
        example: securePassword123
        type: string
      soName:
        example: Doe
        type: string
      uuid:
        type: string
    type: object
info:
  contact: {}
paths:
  /chats/create-chat:
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные для создания чата
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/chats.CreateChatStruct'
      produces:
      - application/json
      responses:
        "200":
          description: successful response
          schema:
            additionalProperties: true
            type: object
        "400":
          description: bad request
          schema:
            additionalProperties: true
            type: object
      summary: Создание чата
      tags:
      - Chats
  /chats/get-chats:
    get:
      consumes:
      - application/json
      description: Получает список чатов для указанного пользователя.
      parameters:
      - description: user_id
        in: query
        name: user_id
        required: true
        type: string
      - description: UUID пользователя
        in: query
        name: uuid
        required: true
        type: string
      - description: Стейт следющей страницы
        in: query
        name: page_state
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: successful response
          schema:
            additionalProperties: true
            type: object
        "400":
          description: bad request
          schema:
            additionalProperties: true
            type: object
      summary: Получение чатов пользователя
      tags:
      - Chats
  /chats/get-chats-secured:
    get:
      consumes:
      - application/json
      description: Получает список чатов для указанного пользователя.
      parameters:
      - description: user_id
        in: query
        name: user_id
        required: true
        type: string
      - description: UUID пользователя
        in: query
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: successful response
          schema:
            additionalProperties: true
            type: object
        "400":
          description: bad request
          schema:
            additionalProperties: true
            type: object
      summary: Получение чатов пользователя
      tags:
      - Chats
  /token/generateToken:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: successful response
          schema:
            additionalProperties: true
            type: object
      summary: Получение токена и uuid
      tags:
      - Tokens
  /user/check-uniqueness-registration-data:
    post:
      consumes:
      - application/json
      description: Проверяет не заняты ли login и Nik
      parameters:
      - description: Данные о пользователе
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/users.UserCUD'
      produces:
      - application/json
      responses:
        "200":
          description: User registered successfully
          schema:
            $ref: '#/definitions/users.ResponseMessage'
      summary: Проверка login и Nik
      tags:
      - Users
  /user/chek-token:
    post:
      consumes:
      - application/json
      description: Проверяет валидность пользователя => сессии
      parameters:
      - description: Данные о токене
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/users.UserCT'
      produces:
      - application/json
      responses:
        "200":
          description: User registered successfully
          schema:
            $ref: '#/definitions/users.ResponseMessage'
        "400":
          description: Invalid request data
          schema:
            $ref: '#/definitions/users.ErrorResponse'
        "500":
          description: Failed to connect to database
          schema:
            $ref: '#/definitions/users.ErrorResponse'
      summary: Проверка токена
      tags:
      - Users
  /user/log-in-with-credentials:
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные пользователя
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/users.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: successful response
          schema:
            additionalProperties: true
            type: object
        "400":
          description: bad request
          schema:
            additionalProperties: true
            type: object
      summary: Аутентификация пользователя по логину и паролю
      tags:
      - Users
  /user/registration:
    post:
      consumes:
      - application/json
      description: Регистрирует пользователя, сохраняя зашифрованные данные и ключ
        в базу данных.
      parameters:
      - description: Данные пользователя
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/users.UserRegistration'
      produces:
      - application/json
      responses:
        "200":
          description: User registered successfully
          schema:
            $ref: '#/definitions/users.ResponseMessage'
        "400":
          description: Invalid request data
          schema:
            $ref: '#/definitions/users.ErrorResponse'
        "500":
          description: Failed to connect to database
          schema:
            $ref: '#/definitions/users.ErrorResponse'
      summary: Регистрация нового пользователя
      tags:
      - Users
swagger: "2.0"
